name: Docker Image CI for GHCR
on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      CONTAINER_REGISTRY_UN: ${{ secrets.AZURE_CONTAINER_REGISTRY_UN }}
      CONTAINER_REGISTRY_PW: ${{ secrets.AZURE_CONTAINER_REGISTRY_PW }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Publish the image to github container registry
        run: |
          docker login --username josephtham --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/josephtham/arithmetic-service:$VERSION --file Dockerfile .
          docker push ghcr.io/josephtham/arithmetic-service:$VERSION
      - name: Publish the image to azure container registry
        run: |
          docker login --username $CONTAINER_REGISTRY_UN --password $secrets.CONTAINER_REGISTRY_PW $CONTAINER_REGISTRY
          docker tag ghcr.io/josephtham/arithmetic-service:$VERSION  $CONTAINER_REGISTRY/arithmetic-service:$VERSION
          docker push $CONTAINER_REGISTRY/arithmetic-service:$VERSION

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy
        run: ./deploy.sh