name: Docker Image CI for GHCR
on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Publish the image to github container registry
        run: |
          echo "${{secrets.ACCESS_TOKEN}}" | docker login ghcr.io -u josephtham --password-stdin
          docker build -t ghcr.io/josephtham/arithmetic-service:$VERSION --file Dockerfile .
          docker push ghcr.io/josephtham/arithmetic-service:$VERSION
      - name: Publish the image to azure container registry
        run: |
          echo "${{secrets.CONTAINER_REGISTRY_PW}}" | docker login ${{secrets.AZURE_CONTAINER_REGISTRY}}.azurecr.io -u ${{secrets.CONTAINER_REGISTRY_UN}} --password-stdin
          docker tag ghcr.io/josephtham/arithmetic-service:$VERSION ${{secrets.AZURE_CONTAINER_REGISTRY}}.azurecr.io/arithmetic-service:$VERSION
          docker push ${{secrets.AZURE_CONTAINER_REGISTRY}}.azurecr.io/arithmetic-service:$VERSION

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy
        env:
          CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          VERSION: ${{ github.sha }}
        run: ./deploy.sh