name: Docker Image CI for GHCR
on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Publish the image to github container registry
        run: |
          docker login --username josephtham --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/josephtham/arithmetic-service:1 --file Dockerfile .
          docker push ghcr.io/josephtham/arithmetic-service:1
      - name: Publish the image to azure container registry
        run: |
          docker login --username p466spring2025josephtham --password ${{secrets.AZURE_CONTAINER_REGISTRY}} p466spring2025josephtham.azurecr.io
          docker tag ghcr.io/josephtham/arithmetic-service:1  p466spring2025josephtham.azurecr.io/arithmetic-service:1
          docker push p466spring2025josephtham.azurecr.io/arithmetic-service:1