name: Docker Image CI for GHCR
on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw clean package
      - name: Publish the image to github container registry
        run: |
          echo "${{secrets.ACCESS_TOKEN}}" | docker login ghcr.io -u josephtham --password-stdin
          docker build -t ghcr.io/josephtham/arithmetic-service:$VERSION --file Dockerfile .
          docker push ghcr.io/josephtham/arithmetic-service:$VERSION
      - name: Publish the image to azure container registry
        run: |
          echo "${{secrets.CONTAINER_REGISTRY_PW}}" | docker login ${{secrets.AZURE_CONTAINER_REGISTRY}} -u ${{secrets.CONTAINER_REGISTRY_UN}} --password-stdin
          docker tag ghcr.io/josephtham/arithmetic-service:$VERSION ${{secrets.AZURE_CONTAINER_REGISTRY}}/arithmetic-service:$VERSION
          docker push ${{secrets.AZURE_CONTAINER_REGISTRY}}/arithmetic-service:$VERSION

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy
        run: ./deploy.sh